name: mtdna_analysis
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  # Bioinformatics tools
  - minimap2
  - lofreq
  - bcftools
  - samtools
  - hyphy
  # Core Python packages
  - biopython
  - pandas
  - numpy
  - scipy
  - pyarrow
  - matplotlib
  - seaborn
  - statsmodels
  - cyvcf2
  - mygene
  - pip
  - pip:
    - matplotlib-venn
    - statannotations
    - adjustText
    - mycolorpy
